export const ACCOUNT_OFFERS_PROCESSING = "ACCOUNT_OFFERS_PROCESSING";

export const SET_ACCOUNT_OFFERS = "SET_ACCOUNT_OFFERS";

export const STOP_SET_ACCOUNT_OFFERS_PROCESSING =
  "STOP_SET_ACCOUNT_OFFERS_PROCESSING";
