name: Cloud Run Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      IMAGE_NAME: gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_APP_NAME }}
      DISABLE_ESLINT_PLUGIN: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build React App
        run: |
          npm i -f
          npm run build
          cp -r ./build ./_deploy/

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker Image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker Image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy ${{ vars.GCP_APP_NAME }} --image $IMAGE_NAME --region us-central1 --platform managed --allow-unauthenticated --cpu 1 --min-instances 1 --max-instances 4 --memory 256Mi --port 8080 --no-use-http2 --set-env-vars NODE_ENV=production --service-account ${{ vars.GCP_ACCOUNT_NAME }}@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com
