name: Automated deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      DISABLE_ESLINT_PLUGIN: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i -f
      - run: npm run build
      - run: cd _deploy && cp -r ../build ./ && zip -rq ../deploy.zip .

      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.APP_NAME }}
          environment_name: ${{ vars.ENV_NAME }}
          version_label: "version-${{github.run_number}}"
          region: us-east-1
          deployment_package: deploy.zip
